@startuml State 2

state "Initialization" as I #LightBlue
I : entry / StartUp or Reset
I : do / Initialization
I : exit / Transition or Fault detected

state "Operational" as O #MediumSeaGreen
O : entry / Transition
O : do / LED on, device working
O : exit / Reset or Fault detected

state "Stopped" as S #IndianRed
O : entry / Fault detected
O : do / LED blinking at 2 Hz
O : exit / Transition


O --> I : Reset
O --> S : Fault detected

I --> O : Transition

S --> O : Set operational
S --> I : Reset

@enduml