@startuml State 1

state "Initialization" as I #LightBlue
I : entry / Initialization
I : do / 
I : exit / 

state "Operational" as O #MediumSeaGreen
O : entry / startUP
O : do / LED on
O : exit / shutDown


O --> I : Reset

I --> O : Transition

@enduml