@startuml State 1

state "Initialization" as I #LightBlue
I : entry / StartUp or Reset
I : do / Initialization
I : exit / Transition

state "Operational" as O #MediumSeaGreen
O : entry / Transition
O : do / LED on, device working
O : exit / Reset


O --> I : Reset

I --> O : Transition

@enduml